- id: '1576093494347'
  alias: Licht kastlamp aan bij zonsondergang
  description: ''
  trigger:
  - event: sunset
    offset: 00:10:00
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - entity_id: light.kastlamp
    service: light.turn_on
- id: '1578501356390'
  alias: Nachtlampje Kim aan
  description: ''
  trigger:
  - platform: time
    at: 07:00:00
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: 06:55:00
    before: 07:10:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: light.nachtlampje_kim
    service: light.turn_on
- id: '1576094288732'
  alias: Nachtlampje Noor aan
  description: ''
  trigger:
  - platform: time
    at: 07:20:00
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: 07:15:00
    before: 07:25:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: light.nachtlampje_noor
    service: light.turn_on
- id: '1576243484410'
  alias: Zet muziek aan bij thuiskomst
  description: ''
  trigger:
  - entity_id: group.family
    from: not_home
    platform: state
    to: home
  condition:
  - after: 09:00:00
    before: '17:00:00'
    condition: time
  - condition: or
    conditions:
    - condition: state
      entity_id: media_player.woonkamer
      state: idle
    - condition: state
      entity_id: media_player.woonkamer
      state: paused
  action:
  - data:
      media_content_id: http://icecast-qmusic.cdp.triple-it.nl//Qmusic_be_live_96.mp3
      media_content_type: music
      entity_id: media_player.woonkamer
    service: media_player.play_media
- id: '1578158381176'
  alias: Welkom thuis
  description: ''
  trigger:
  - entity_id: group.family
    from: not_home
    platform: state
    to: home
  action:
  - data:
      entity_id: media_player.woonkamer
    service: media_player.turn_on
  - delay: 00:00:02
  - data:
      entity_id: media_player.woonkamer
      language: nl
      message: Hallo knapperd, welkom thuis!
    service: tts.google_translate_say
  - delay: 00:00:04
  - data:
      entity_id: media_player.woonkamer
    service: media_player.turn_off
- id: '1578251418685'
  alias: Lichten inkom en keuken aan bij thuiskomst
  description: ''
  trigger:
  - entity_id: group.family
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: light.inkom
    entity_id: light.keuken
    service: light.turn_on
- id: '1586875920509'
  alias: Notificatie afval
  description: ''
  trigger:
  - at: '20:00:00'
    platform: time
  condition:
    condition: or
    conditions:
    - condition: template
      value_template: "{% if is_state('sensor.ophaalkalender_vandaag', 'pmd') %}true{% endif %}"
    - condition: template
      value_template: "{% if is_state('sensor.ophaalkalender_vandaag', 'restafval') %}true{% endif %}"
    - condition: template
      value_template: "{% if is_state('sensor.ophaalkalender_vandaag', 'papier') %}true{% endif %}"
  action:
  - data:
      message: Herinnering:Deze nacht wordt {{states.sensor.ophaalkalender_vandaag.state}} opgehaald!
    service: notify.mobile_app_nokia_7_plus
  - data:
      message: Herinnering:Deze nacht wordt {{states.sensor.ophaalkalender_vandaag.state}} opgehaald!
    service: notify.mobile_app_iphone_kim  
  - data:
      entity_id: group.media_player
    service: media_player.turn_on
  - delay: '00:00:02'
  - data:
      entity_id: group.media_player
      language: nl
      message: Herinnering, Deze nacht wordt {{states.sensor.ophaalkalender_vandaag.state}} opgehaald!
    service: tts.google_translate_say
  - delay: '00:00:04'
  - data:
      entity_id: group.media_player
    service: media_player.turn_off 