default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages


frontend:
  themes: !include_dir_merge_named themes
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml

customizer:
  custom_ui: local
  
hacs:
  token: !secret hacs_token
  appdaemon: true
  
# Text to speech

tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

sensor:
  - platform: unifigateway
    host: !secret unifi_host
    site_id: !secret unifi_site
    username: !secret unifi_username  
    password: !secret unifi_password
    monitored_conditions:
      - www
      - lan
      - wan
      - wlan
      - vpn
      - alerts
      - firmware
      
remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony


  