default_config:

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.107.0/24
        - 192.168.99.0/24
  

frontend:
  themes: !include_dir_merge_named themes
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
   # Add more dashboards
  dashboards:
    lovelace-test: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboard_test.yaml
      title: Test
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false
    lovelace-tablet: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboard_tablet.yaml
      title: Tablet
      icon: mdi:tablet-ipad
      show_in_sidebar: true
      require_admin: false
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key

hacs:
  token: !secret hacs_token
  appdaemon: true
  

# Text to speech
tts:
  - platform: google_translate
    base_url: !secret tts_base_url


############################
## Includes
############################

group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
light: !include includes/lights.yaml
switch: !include includes/switches.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_datetime: !include includes/input_datetime.yaml
automation: !include_dir_merge_list automations/
cloud: !include includes/cloud.yaml

#############################
  
rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command
python_script:

browser_mod: