default_config:

http:
  use_x_forwarded_for: true
  trusted_proxies: !secret http_trusted_proxies

homeassistant:
  packages: !include_dir_named packages
  customize: !include customize.yaml
  auth_providers:
    - type: trusted_networks
      trusted_networks:
        - 192.168.107.0/24
        - 192.168.99.0/24
    - type: homeassistant    
  auth_mfa_modules:
    - type: totp
      name: Authenticator app
    - type: notify
      message: "Access token: {}"     

  
lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
   # Add more dashboards
  dashboards:
    lovelace-tablet: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboard_smartphone.yaml
      title: Smartphone
      icon: mdi:cellphone
      show_in_sidebar: true
      require_admin: false
    lovelace-kids: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboard_kids.yaml
      title: Kids
      icon: mdi:human-male-boy
      show_in_sidebar: true
      require_admin: false


############################
## Includes
############################

group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
light: !include includes/lights.yaml
switch: !include includes/switches.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
input_text: !include includes/input_text.yaml
input_number: !include includes/input_number.yaml
input_datetime: !include includes/input_datetime.yaml
media_player: !include includes/media_players.yaml
automation: !include_dir_merge_list automations/
notify: !include includes/notify.yaml
alert: !include includes/alert.yaml
google_assistant: !include includes/google_assistant_integration.yaml

#############################

tts:
  - platform: google_cloud
    key_file: !secret google_cloud_tts
    language: nl-NL
    gender: male
    voice: nl-BE-Wavenet-B

frontend:
  themes: !include_dir_merge_named themes

panel_iframe:
  dsmr:
    title: "DSMR Reader"
    url: !secret url_dsmr
    icon: mdi:flash
    
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

spotcast:
  sp_dc: !secret sp_dc
  sp_key: !secret sp_key
  
rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command

browser_mod:
  prefix: "browser_"
  devices:
    41b5a475-fe0bd9fc:
      name: tablet
  disable:
    - light
    - media_player
  
python_script:

ffmpeg:

wake_on_lan: # enables `wake_on_lan` integration
  
