default_config:

homeassistant:
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
  

frontend:
  themes: !include_dir_merge_named themes
  
# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

lovelace:
  mode: yaml
  resources: !include lovelace/resources.yaml
   # Add more dashboards
  dashboards:
    lovelace-test: # Needs to contain a hyphen (-)
      mode: yaml
      filename: dashboard_test.yaml
      title: Test
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: false
      
customizer:
  custom_ui: local
  
google:
  client_id: !secret google_id
  client_secret: !secret google_secret

hacs:
  token: !secret hacs_token
  appdaemon: true
  
# Text to speech

tts:
  - platform: google_translate
    base_url: !secret tts_base_url


############################
## Includes
############################

group: !include includes/groups.yaml
script: !include includes/scripts.yaml
scene: !include includes/scenes.yaml
light: !include includes/lights.yaml
switch: !include includes/switches.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
automation: !include_dir_merge_list automations/
cloud: !include includes/cloud.yaml  


#############################
  
remote:
  - platform: harmony
    name: Harmony Hub
    host: !secret harmony

rest_command:
  kiosk_command:
    url: !secret rest_url_kiosk_command
python_script:

