decluttering_templates:
  notification_template:     # This is the name of a template
    card:
      type: custom:button-card
      name: '[[name]]'
      size: 100%
      show_state: false
      show_label: false
      layout: icon_name
      tap_action: 
        action: none
      hold_action: 
        action: none
      styles:
        card:
          - --ha-card-background: rgba(0,0,0,0.0)
          - box-shadow: none
          - height: 45px
        name:
          - font-size: 18px
          - font-family: Helvetica
          - color: var(--primary-color)
          - justify-self: start
          - font-weight: normal
        grid: 
          - grid-template-areas: '"i n"'
          - grid-template-columns: 8% 1fr
          - grid-template-rows: 1fr
        
background: var(--background-image)
title: Thuis
kiosk_mode:
  hide_header: true
views:
  - !include lovelace/views/Home.yaml

button_card_templates:
  automation:
    show_label: true
    show_state: true
    size: 30%
    color_type: card
    styles:
      card:
        - font-size: 14px
        - height: 120px
        - width: 120px
      img_cell:
        - justify-content: start
        - align-items: start
        - padding-left: 20px
        - height: 40px
      name:
        - white-space: normal
        - max-height: 2.4em
        - justify-self: start
        - padding-left: 10px
        - font-weight: bold
        - text-align: left
        - align-self: end
      state:
        - justify-self: start
        - padding-left: 10px
      grid:
        - grid-template-areas: '"i" "n" "s"'
        - grid-template-rows: 1fr 1fr min-content 
    state:
    - value: 'on'
      styles:
        state:
          - color: 'rgba(0, 0, 0, 1)'
        icon: 
          - color: 'rgb(255, 140, 0)'
        card: 
          - background: 'rgb(95, 155, 234)'
        name:
          - color: 'rgba(255, 255, 255, 1)'
    - value: 'off'
      styles:
        state:
          - color: 'rgba(0, 0, 0, 0.4)'
        icon:
          - color: 'rgb(255, 255, 255)'
        card:
          - background: 'rgb(221, 221, 211)'
        name:
          - color: 'rgba(0, 0, 0, 1)'
