background: var(--background-image)
custom_header:
  background: 'rgba(155, 155, 155, 0.25)'
  button_text: none
  custom_header:
  header_text: >-
    <style>
    #flipper {color:#999;}
    #flip {height:24px;overflow:hidden;}
    #flip > div > div {color:#fff;height:24px;margin-bottom:24px;display:inline-block;}
    #flip div:first-child {animation: show 10s linear infinite;}
    @keyframes show {
    0% {margin-top:-144px;}
    5% {margin-top:-96px;}
    33% {margin-top:-96px;}
    38% {margin-top:-48px;}
    66% {margin-top:-48px;}
    76% {margin-top:0px;}
    100% {margin-top:0px;}}
    #flipper p {position:fixed;color:#999; }
    </style>
    <div id=flipper><div id=flip><div><div>
    Huidige buitentemperatuur: {{states('sensor.temperature')}}°C</div></div><div><div>
    {{states('sensor.greeting')}}</div></div><div><div>
    {{states('sensor.afval')}}</div></div><div><div>
  compact_mode: false
  reverse_tab_direction: true
  reverse_button_direction: true
  options_hide: true
  show_tabs:
   - Home
  shadow: false
title: Thuis
views:
  - !include lovelace/views/01-home.yaml
  - !include lovelace/views/02-lichten.yaml
  - !include lovelace/views/03-cameras.yaml
  - !include lovelace/views/04-entertainment.yaml
  - !include lovelace/views/05-cinema.yaml
  - !include lovelace/views/06-automatisaties.yaml
  - !include lovelace/views/13-server.yaml
  - !include lovelace/views/14-network.yaml
  - !include lovelace/views/15-energie.yaml
  - !include lovelace/views/20-persoon1.yaml
  - !include lovelace/views/21-persoon2.yaml
  
  
