##########################
## Tuinverlichting
##########################
- id: turn_on_garden_lights_in_the_evening
  alias: "Lichten: Tuinverlichting aan 's avonds"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: light.tuinverlichting
    
- id: turn_on_garden_lights_on_movement_in_the_morning
  alias: "Lichten: Tuinverlichting 's morgens aan op beweging"
  trigger:
    platform: state
    entity_id: binary_sensor.det_living
    to: "on"
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "06:00:00"
          before: "08:00:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 1
        - condition: state
          entity_id: light.tuinverlichting
          state: "off"
        - condition: state
          entity_id: input_boolean.verlichting_tuin
          state: "off"  
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.tuinverlichting  
        - input_boolean.verlichting_tuin

- id: turn_off_garden_lights_in_the_morning
  alias: "Lichten: Tuinverlichting 's morgens uit"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 1
  condition:
    - condition: state
      entity_id: light.tuinverlichting
      state: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: light.tuinverlichting

##########################
## Gevelverlichting
##########################
- id: turn_on_exterior_wall_light
  alias: "Lichten: Gevelverlichting aan"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
  - service: homeassistant.turn_on
    entity_id: light.licht_voordeur    

##########################
## Lichten inkom
##########################

- id: turn_on_spotlights_after_press
  alias: "Lichten: Licht inkom aan na induwen drukknop"
  trigger:
    - entity_id: switch.inkom
      platform: state
      to: 'on'
  action:
  - data:  
      entity_id: light.inkom
    service: light.toggle

- alias: "Lichten: Spots inkom aan bij beweging"
  trigger:
  - entity_id: binary_sensor.det_inkom
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: light.inkom
    service: light.turn_on
 
- alias: "Lichten: Spots inkom uit 30 seconden na laatste beweging" 
  trigger:
  - entity_id: binary_sensor.det_inkom
    platform: state
    to: 'off'
    for:
      seconds: 30
  action:
    service: light.turn_off
    entity_id: light.inkom    


##########################
## Verlichting eetplaats
##########################
- id: turn_on_dining_room_on_movement
  alias: "Lichten: Eetplaats aan op beweging"
  trigger:
    platform: state
    entity_id: binary_sensor.det_living
    to: "on"
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "06:00:00"
          before: "08:00:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 1
        - condition: state
          entity_id: light.eettafel
          state: "off"
        - condition: state
          entity_id: input_boolean.verlichting_eettafel
          state: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: 
        - light.eettafel
        - input_boolean.verlichting_eettafel
      


##########################
## Kastlamp
##########################
- alias: "Lichten: Kastlamp aan bij zonsondergang"
  description: ''
  trigger:
  - event: sunset
    offset: "-00:05:00"
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - entity_id: light.kastlamp
    service: light.turn_on
    

########################################
## Hal
########################################    

- id: turn_on_stairlights_on_movement
  alias: "Lichten: Trap aan op beweging"
  trigger:
    platform: state
    entity_id: binary_sensor.det_boven
    to: "on"
  condition:
    - condition: and
      conditions:
        - condition: time
          after: "06:00:00"
          before: "08:30:00"
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 6
        - condition: state
          entity_id: light.trap_gelijkvloers
          state: "off"  
  action:
    - service: homeassistant.turn_on
      entity_id: light.trap_gelijkvloers
      
- id: turn_off_stairlights_after_last_movement
  alias: "Lichten: Trap uit 30 seconden na laatste beweging"
  trigger:
    platform: state
    entity_id: binary_sensor.det_boven
    to: "off"
    for:
      seconds: 30
  condition:
    - condition: state
      entity_id: light.trap_gelijkvloers
      state: "on"
  action:
    service: homeassistant.turn_off
    entity_id: light.trap_gelijkvloers

    

########################################
## Lichten dressing
########################################    
- id: 'Zet spots dressing om na duwen op drukknop'
  alias: "Lichten: Licht dressing aan na induwen drukknop"
  trigger:
    - entity_id: switch.dressing
      platform: state
      to: 'on'
  action:
  - data:  
      entity_id: light.dressing
    service: light.toggle
    

########################################
## Lichten cinema
########################################    
- id: 'Turn_on_cinema_seat_lights_after_press'
  alias: "Lichten: Licht cinema zetel aan na induwen drukknop"
  trigger:
    - entity_id: switch.cinema_zetel
      platform: state
      to: 'on'
  action: 
  - data:  
      entity_id: light.cinema
    service: light.toggle 

- id: Turn_on_cinema_screen_lights_after_press
  alias: "Lichten: Licht cinema scherm aan na induwen drukknop"
  trigger:
    - entity_id: switch.cinema_scherm
      platform: state
      to: 'on'
  action: 
  - data:  
      entity_id: light.cinema_scherm
    service: light.toggle


########################################
## Alle lichten uit
########################################    
- id: Turn_off_all_lights_after_press
  alias: "Lichten: Alle verlichting uit"
  trigger:
    - entity_id: switch.alle_lichten_uit
      platform: state
      from: 'off'
      to: 'on'
  action: 
  - data:  
      entity_id: all
    service: light.turn_off
    

########################################
## Kerstverlichting
########################################
   
- id: turn_on_buxus_christmas_lights_in_the_morning
  alias: "Lichten: Kerstverlichting buxus 's morgens aan"
  trigger:
    platform: time
    at: "07:00:00"
  condition:
    - condition: and
      conditions:
        - condition: numeric_state
          entity_id: sun.sun
          attribute: elevation
          below: 1
        - condition: state
          entity_id: switch.kerstverlichting_buxus
          state: "off"
  action:
    - service: homeassistant.turn_on
      entity_id: switch.kerstverlichting_buxus  

- id: turn_off_buxus_christmas_lights_in_the_morning
  alias: "Lichten: Kerstverlichting buxus 's morgens uit"
  trigger:
    platform: numeric_state
    entity_id: sun.sun
    value_template: "{{ state_attr('sun.sun', 'elevation') }}"
    above: 1
  condition:
    - condition: state
      entity_id: switch.kerstverlichting_buxus
      state: "on"
  action:
    - service: homeassistant.turn_off
      entity_id: switch.kerstverlichting_buxus   

- id: turn_on_buxus_christmas_lights_at_night
  alias: "Lichten: Kerstverlichting buxus aan 's avonds"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
  - service: homeassistant.turn_on
    entity_id: switch.kerstverlichting_buxus 
    

########################################
## Vakantie lichten
########################################
- id: 'Turn on vacation lights to simulate presence'
  alias: "Lichten: Vakantie lichten willekeurig aan"
  initial_state: on
  trigger:
    platform: time
    at: input_datetime.time_vakantielichten_start
  condition:
    - condition: state
      entity_id: input_boolean.vakantiemodus
      state: 'on'
  action:
    - delay: '00:{{ range(1,30) | random | int }}:00'
    # Toggling random entity state
    - service: homeassistant.turn_on
      data:
        entity_id: "{{ state_attr('group.simulation_lights_on','entity_id') | random }}"     
    - service: notify.mobile_devices
      data:
        message: Ik heb je simulatielichten boven aangestoken om {{ now().strftime('%H') }}:{{now().strftime('%M') }}.

- id: 'Turn off vacation lights to simulate presence'
  alias: "Lichten: Vakantie lichten uit"
  initial_state: on
  trigger:
    platform: time
    at: input_datetime.time_vakantielichten_end
  condition:
    - condition: state
      entity_id: input_boolean.vakantiemodus
      state: 'on'
  action:
    - delay: '00:{{ range(1,30) | random | int }}:00'
    - service: homeassistant.turn_off
      entity_id: group.simulation_lights_off
    - service: notify.mobile_devices
      data:
        message: Ik heb je aanwezigheidssimulatie met lichten gestopt om {{ now().strftime('%H') }}:{{now().strftime('%M') }}.
        
        
########################################
## Reset boolean verlichting
########################################

- id: turn_off_boolean_lights
  alias: "Lichten: Boolean verlichting uit"
  initial_state: 'true'
  trigger:
    platform: time
    at: "09:30:00"
  action:
  - service: homeassistant.turn_off
    entity_id: 
      - input_boolean.verlichting_eettafel
      - input_boolean.verlichting_tuin


        
