##########################
## Tuinverlichting
##########################
- id: tuinverlichting_aan
  alias: "Tuinverlichting aan"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - service: homeassistant.turn_on
    entity_id: light.tuinverlichting


##########################
## Gevelverlichting
##########################
- id: gevelverlichting_aan
  alias: "Gevelverlichting aan"
  initial_state: 'on'
  trigger:
    platform: sun
    event: sunset
    offset: "-00:05:00"
  action:
  - service: homeassistant.turn_on
    entity_id: light.licht_voordeur    


##########################
## Kastlamp
##########################
- id: '1576093494347'
  alias: Licht kastlamp aan bij zonsondergang
  description: ''
  trigger:
  - event: sunset
    offset: "-00:05:00"
    platform: sun
  condition:
  - condition: state
    entity_id: group.family
    state: home
  action:
  - entity_id: light.kastlamp
    service: light.turn_on
    
    
##########################
## Nachtlampjes
##########################

- id: '1578501356390'
  alias: Nachtlampje Kim aan
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_wake_up_kim
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: 06:55:00
    before: 07:10:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: light.nachtlampje_kim
    service: light.turn_on


- id: '1576094288732'
  alias: Nachtlampje Noor aan
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_wake_up_noor
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: 07:10:00
    before: 07:25:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: light.nachtlampje_noor
    service: light.turn_on


- id: 'Turn on nightlight'
  alias: Nachtlampje Arne aan
  description: ''
  trigger:
  - platform: time
    at: input_datetime.time_wake_up_arne
  condition:
  - condition: state
    entity_id: group.family
    state: home
  - condition: time
    after: 07:10:00
    before: 07:25:00
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - data:
      entity_id: light.nachtlampje_arne
    service: light.turn_on


##########################
## Lichten inkom
##########################

- alias: Lichten inkom aan bij beweging
  trigger:
  - entity_id: binary_sensor.det_inkom
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
  - data:
      entity_id: light.inkom
    service: light.turn_on
 
- alias: Lichten inkom uit 2 minuten na laatste beweging 
  trigger:
  - entity_id: binary_sensor.det_inkom
    platform: state
    to: 'off'
    for:
      seconds: 30
  action:
    service: light.turn_off
    entity_id: light.inkom    
    
########################################
## Alle lichten uit
########################################    
- id: 'Zet alle verlichting uit na duwen op drukknop'
  alias: Alle verlichting uit
  trigger:
    - entity_id: switch.alle_lichten_uit
      platform: state
      from: 'off'
      to: 'on'
  action: 
  - data:  
      entity_id: all
    service: light.turn_off
    
    
########################################
## Lichtbediening inkom
########################################    
- id: 'Zet spots inkom om na duwen op drukknop'
  alias: Licht inkom om
  trigger:
    - entity_id: switch.inkom
      platform: state
      to: 'on'
  action:
  - data:  
      entity_id: light.inkom
    service: light.toggle


########################################
## Lichtbediening dressing
########################################    
- id: 'Zet spots dressing om na duwen op drukknop'
  alias: Licht dressing om
  trigger:
    - entity_id: switch.dressing
      platform: state
      to: 'on'
  action:
  - data:  
      entity_id: light.dressing
    service: light.toggle
    

########################################
## Lichtbediening cinema
########################################    
- id: 'Zet spots cinema zetel om na duwen op drukknop'
  alias: Licht cinema zetel om
  trigger:
    - entity_id: switch.cinema_zetel
      platform: state
      to: 'on'
  action: 
  - data:  
      entity_id: light.cinema
    service: light.toggle 

- id: 'Zet spots cinema scherm om na duwen op drukknop'
  alias: Licht cinema scherm om
  trigger:
    - entity_id: switch.cinema_scherm
      platform: state
      to: 'on'
  action: 
  - data:  
      entity_id: light.cinema_scherm
    service: light.toggle

    
########################################
## Vakantie lichten
########################################
- id: 'Turn on vacation lights to simulate presence'
  alias: Vakantie lichten willekeurig aan
  initial_state: on
  trigger:
    platform: time
    at: input_datetime.time_vakantielichten_start
  condition:
    - condition: state
      entity_id: input_boolean.vakantiemodus
      state: 'on'
  action:
    - delay: '00:{{ range(01,30) | random | int }}:00'
    # Toggling random entity state
    - service: homeassistant.turn_on
      data:
        entity_id: "{{ state_attr('group.simulation_lights_on','entity_id') | random }}"     
    - service: notify.mobile_app_nokia_7_plus
      data:
        message: Ik heb je simulatielichten boven aangestoken om {{ now().strftime('%H') }}:{{now().strftime('%M') }}.

- id: 'Turn off vacation lights to simulate presence'
  alias: Vakantie lichten uit
  initial_state: on
  trigger:
    platform: time
    at: input_datetime.time_vakantielichten_end
  condition:
    - condition: state
      entity_id: input_boolean.vakantiemodus
      state: 'on'
  action:
    - delay: '00:{{ range(01,30) | random | int }}:00'
    - service: homeassistant.turn_off
      entity_id: group.simulation_lights_off
    - service: notify.mobile_app_nokia_7_plus
      data:
        message: Ik heb je aanwezigheidssimulatie met lichten gestopt om {{ now().strftime('%H') }}:{{now().strftime('%M') }}.
