#############################
## Notify Group all mobiles #
#############################
- platform: group
  name: mobile_devices
  services:
    - service: mobile_app_sm_a505fn
    - service: mobile_app_moto_g_8_plus

#############################
## Notify Google TTS        #
#############################
- platform: tts
  name: tts_woonkamer
  tts_service: tts.microsoft_say
  media_player: media_player.woonkamer