#############################
## Notify Group all mobiles #
#############################
- platform: group
  name: mobile_devices
  services:
    - service: mobile_app_smartphone_stijn
    - service: mobile_app_smartphone_kim
- name: script_thefes
  platform: file
  filename: /config/script_thefes.txt
  timestamp: true
