#############################
## Notify Group all mobiles #
#############################
- platform: group
  name: mobile_devices
  services:
    - service: mobile_app_smartphone_stijn
    - service: mobile_app_oneplus_nord

