action: fire-dom-event
browser_mod:
  command: popup
  title: Information
  hide_header: true
  deviceID: this
  style:
    .: |
      :host .content {
        width: calc(385px + 385px + 385px);
        max-width: 90vw;
      }
    $: |
      .mdc-dialog .mdc-dialog__container .mdc-dialog__surface {
        background: none !important;
      }
  card:
    type: custom:layout-card
    column_num: 1
    column_width: [385]
    layout: vertical
    cards:
      - type: picture-glance
        title: Voordeur
        aspect_ratio: 55%
        entities: []
        entity: camera.deurbel
        name: Deurbel
        camera_image: camera.deurbel
        tap_action:
          action: more-info
      - type: picture-glance
        title: Tuin
        aspect_ratio: 55%
        entities: []
        entity: camera.tuin
        name: Achtertuin
        camera_image: camera.tuin
        tap_action:
          action: more-info    
      