sensor:
  - platform: template
    sensors:
      wasmachine_status:
        value_template: "{{ states('input_select.wasmachine_status') }}"
        friendly_name: 'Wasmachine status'
      droogkast_status:
        value_template: "{{ states('input_select.droogkast_status') }}"
        friendly_name: 'Droogkast status'      
      