recorder:
  purge_keep_days: 5
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date
      
logger:
  default: info
  logs:
    custom_components.eufy_security: debug
