#### CUSTOMIZE #################################################################

sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
    postcode: !secret recycleapp_postcode
    streetnumber: !secret recycleapp_streetnumber
    streetname: !secret recycleapp_streetname
    dutch: 1
    dateformat: '%d-%B'
    dateonly: 0
    dayofweek: 0
    builtinicons: 0
    upcomingsensor: 1
  - platform: template
    sensors:
      afval:
        friendly_name: Afval vandaag
        icon_template: mdi:delete
        value_template: >
          {% if is_state('sensor.recycleapp_vandaag', 'pmd') %}
            Deze avond pmd buiten zetten!
          {% elif is_state('sensor.recycleapp_vandaag', 'restafval') %}
            Deze avond restafval buiten zetten!
          {% elif is_state('sensor.recycleapp_vandaag', 'papier') %}
            Deze avond papier en karton buiten zetten!
          {% endif %} 