#### CUSTOMIZE #################################################################

sensor:
  - platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - restafval
      - papier
      - pmd
    postcode: !secret recycleapp_postcode
    streetnumber: !secret recycleapp_streetnumber
    streetname: !secret recycleapp_streetname
    dutch: 1
    dateformat: '%d-%B'
    dateonly: 0
    dayofweek: 0
    builtinicons: 0
    upcomingsensor: 1
 