#### CUSTOMIZE #################################################################

sensor:
  - platform: afvalbeheer
    wastecollector: ophaalkalender
    resources:
      - restafval
      - papier
      - pmd
    postcode: !secret ophaalkalender_postcode
    streetname: !secret ophaalkalender_streetname
    dutch: 1
    dateformat: '%d-%B'
    dateonly: 0
    dayofweek: 0
    builtinicons: 1
    upcomingsensor: 1
  - platform: template
    sensors:
      afval:
        entity_id: sensor.ophaalkalender_vandaag
        friendly_name: Afval vandaag
        icon_template: mdi:delete
        value_template: >
          {% if is_state('sensor.ophaalkalender_vandaag', 'pmd') %}
            Deze avond pmd buiten zetten!
          {% elif is_state('sensor.ophaalkalender_vandaag', 'restafval') %}
            Deze avond restafval buiten zetten!
          {% elif is_state('sensor.ophaalkalender_vandaag', 'papier') %}
            Deze avond papier en karton buiten zetten!
          {% endif %} 