sensor:
  - platform: dsmr_reader
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
  - platform: template
    sensors:
      date_long: 
        friendly_name: 'Datum'
        value_template: >
          {% set month = ["Januari", "Februari", "Maart", "April", "Mei", "Juni", "July", "Augustus", "September", "Oktober", "November", "December"][now().month-1] %}
          {{ now().day }} {{ month }} {{ now().year }}
        icon_template: mdi:calendar-clock
      date_short: 
        friendly_name: 'Datum Kort'
        value_template: >
          {% set d = states('sensor.date_long').split() %}
          {{ d[0] }} {{ d[1][:3] }} {{ d[2] }}
        icon_template: mdi:calendar-clock 
      temperature: 
        unit_of_measurement: °C
        value_template: "{{ state_attr('weather.thuis', 'temperature') }}"        
      greeting:
        value_template: >
          {% set state = states('sensor.time') %}
          {% if '00:00' <= state  < '06:00' %}
            Goeienacht !
          {% elif '06:00' <= state  < '12:00' %}
            Goeiemorgen !
          {% elif '12:00' <= state  < '18:00' %}
            Goeiemiddag !
          {% else %}
            Goeieavond !
          {% endif %}    
      postbus:
        value_template: >
          {{ 'open' if is_state('input_boolean.brievenbus', 'on') or is_state('input_boolean.pakjesbus', 'on')
             else 'closed' }}
        friendly_name: Post    
      solar_angle:
        friendly_name: "Stand zon"
        unit_of_measurement: 'graden'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      sunrise:
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"


#### ENERGIE MONITORING #######################################################
  - platform: template
    sensors:
      dagelijks_energie:
        friendly_name: Dagelijks Energie
        unit_of_measurement: kWh
        value_template: "{{ states('dagelijks_energie_dagtarief')|float + states('dagelijks_energie_nachttarief')|float }}"
      maandelijsk_energie:
        friendly_name: Maandelijks Energie
        unit_of_measurement: kWh
        value_template: "{{ states('maandelijks_energie_dagtarief')|float + states('maandelijks_energie_nachttarief')|float }}"
      huidig_stroomverbruik_watt:
        friendly_name: "Huidig Stroomverbruik Watt"
        unit_of_measurement: 'W'
        value_template: "{{(states('sensor.dsmr_reading_electricity_currently_delivered') | float * 1000) | round(0)}}"
      huidig_stroomopbrengst_watt:
        friendly_name: "Huidig Stroomopbrengst Watt"
        unit_of_measurement: 'W'
        value_template: "{{(states('sensor.dsmr_reading_electricity_currently_returned') | float * 1000) | round(0)}}"

#### SERVER MONITORING #######################################################
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

#### COUNT ENTITIES ##########################################################
  - platform: template
    sensors:
      count_automations:
        friendly_name: Automations
        icon_template: mdi:robot
        value_template: "{{ states.automation | count }}"
      count_binary_sensors:
        friendly_name: Binary Sensors
        icon_template: mdi:contrast-circle
        value_template: "{{ states.binary_sensor | count }}"
      count_device_trackers:
        friendly_name: Device Trackers
        icon_template: mdi:radar
        value_template: "{{ states.device_tracker | count }}"
      count_lights:
        friendly_name: Lights
        icon_template: mdi:lightbulb-group
        value_template: "{{ states.light | count }}"
      count_scripts:
        friendly_name: Scripts
        icon_template: mdi:script-text
        value_template: "{{ states.script | count }}"
      count_sensors:
        friendly_name: Sensors
        icon_template: mdi:leak
        value_template: "{{ states.sensor | count }}"
      count_switches:
        friendly_name: Switches
        icon_template: mdi:light-switch
        value_template: "{{ states.switch | count }}"
      count_zones:
        friendly_name: Zones
        icon_template: mdi:map-marker-radius
        value_template: "{{ states.zone | count }}"
      
