sensor:
  - platform: dsmr_reader
  - platform: time_date
    display_options:
      - time
      - date
      - date_time
  - platform: template
    sensors:
      date_long: 
        friendly_name: 'Datum'
        value_template: >
          {% set month = ["Januari", "Februari", "Maart", "April", "Mei", "Juni", "July", "Augustus", "September", "Oktober", "November", "December"][now().month-1] %}
          {{ now().day }} {{ month }} {{ now().year }}
        icon_template: mdi:calendar-clock
      date_short: 
        friendly_name: 'Datum Kort'
        value_template: >
          {% set d = states('sensor.date_long').split() %}
          {{ d[0] }} {{ d[1][:3] }} {{ d[2] }}
        icon_template: mdi:calendar-clock 
      temperature: 
        unit_of_measurement: °C
        value_template: "{{ state_attr('weather.thuis', 'temperature') }}"        
      greeting:
        value_template: >
          {% set state = states('sensor.time') %}
          {% if '00:00' <= state  < '06:00' %}
            Goeienacht !
          {% elif '06:00' <= state  < '12:00' %}
            Goeiemorgen !
          {% elif '12:00' <= state  < '18:00' %}
            Goeiemiddag !
          {% else %}
            Goeieavond !
          {% endif %}    
      postbus:
        value_template: >
          {{ 'open' if is_state('input_boolean.brievenbus', 'on') or is_state('input_boolean.pakjesbus', 'on')
             else 'closed' }}
        friendly_name: Post    
      solar_angle:
        friendly_name: "Stand zon"
        unit_of_measurement: 'graden'
        value_template: "{{ state_attr('sun.sun', 'elevation') }}"
      sunrise:
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"


#### ENERGIE MONITORING #######################################################
  - platform: template
    sensors:
      dagelijks_energie:
        friendly_name: Dagelijks Energie
        unit_of_measurement: kWh
        value_template: "{{ states('dagelijks_energie_dagtarief')|float + states('dagelijks_energie_nachttarief')|float }}"
      maandelijsk_energie:
        friendly_name: Maandelijks Energie
        unit_of_measurement: kWh
        value_template: "{{ states('maandelijks_energie_dagtarief')|float + states('maandelijks_energie_nachttarief')|float }}"
      huidig_stroomverbruik_watt:
        friendly_name: "Huidig Stroomverbruik Watt"
        unit_of_measurement: 'W'
        value_template: "{{(states('sensor.dsmr_reading_electricity_currently_delivered') | float * 1000) | round(0)}}"
      huidig_stroomopbrengst_watt:
        friendly_name: "Huidig Stroomopbrengst Watt"
        unit_of_measurement: 'W'
        value_template: "{{(states('sensor.dsmr_reading_electricity_currently_returned') | float * 1000) | round(0)}}"

#### SERVER MONITORING #######################################################
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

#### COUNT ENTITIES ##########################################################
  - platform: template
    sensors:
      current_media_players_on:
        friendly_name: Aantal mediaspelers aan
        unit_of_measurement: 'on'
        value_template: >
          {% set media_players = [
            states.media_player.woonkamer,
            states.media_player.woonkamer_mini,
            states.media_player.keuken,
            states.media_player.badkamer,
            states.media_player.bureau,
            states.media_player.slaapkamer,
            states.media_player.slaapkamer_arne,
            states.media_player.slaapkamer_noor,
            ] %}
          {{ media_players | selectattr('state','eq','playing') | list | count }}  
      current_lights_on:
        friendly_name: Aantal lampen aan
        unit_of_measurement: 'on'
        value_template: >
          {% set lights = [
            states.light.tuinverlichting,
            states.light.licht_voordeur,
            states.light.licht_achterdeur,
            states.light.vijververlichting,
            states.light.inkom,
            states.light.inkom_wand,
            states.light.eettafel,
            states.light.zithoek,
            states.light.kastlamp,
            states.light.tv_wand,
            states.light.bench,
            states.light.keuken,
            states.light.keuken_wand,
            states.light.keukenkast,
            states.light.trap_gelijkvloers,
            states.light.trap_verdieping,
            states.light.hal_plafond,
            states.light.hal_wand,
            states.light.douche,
            states.light.lavabo,
            states.light.bad,
            states.light.douche_kids,
            states.light.lavabo_kids,
            states.light.bureau,
            states.light.slaapkamer,
            states.light.nachtlampje_kim,
            states.light.dressing,
            states.light.slaapkamer_arne,
            states.light.slaapkamer_noor,
            states.light.cinema,
            states.light.cinema_scherm,
            states.light.speelkamer,
            states.light.technische_ruimte,
            ] %}
          {{ lights | selectattr('state','eq','on') | list | count }}