sensor:
#### SERVER MONITORING #######################################################
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: "/"
      - type: memory_use_percent
      - type: processor_use

#### COUNT ENTITIES ##########################################################
  - platform: template
    sensors:
      count_automations:
        entity_id: sensor.date
        friendly_name: Automations
        icon_template: mdi:robot
        value_template: "{{ states.automation | count }}"
      count_binary_sensors:
        entity_id: sensor.date
        friendly_name: Binary Sensors
        icon_template: mdi:contrast-circle
        value_template: "{{ states.binary_sensor | count }}"
      count_device_trackers:
        entity_id: sensor.date
        friendly_name: Device Trackers
        icon_template: mdi:radar
        value_template: "{{ states.device_tracker | count }}"
      count_lights:
        entity_id: sensor.date
        friendly_name: Lights
        icon_template: mdi:lightbulb-group
        value_template: "{{ states.light | count }}"
      count_scripts:
        entity_id: sensor.date
        friendly_name: Scripts
        icon_template: mdi:script-text
        value_template: "{{ states.script | count }}"
      count_sensors:
        entity_id: sensor.date
        friendly_name: Sensors
        icon_template: mdi:leak
        value_template: "{{ states.sensor | count }}"
      count_switches:
        entity_id: sensor.date
        friendly_name: Switches
        icon_template: mdi:light-switch
        value_template: "{{ states.switch | count }}"
      count_zones:
        entity_id: sensor.date
        friendly_name: Zones
        icon_template: mdi:map-marker-radius
        value_template: "{{ states.zone | count }}"
      
#### CONNECTED DEVICES #######################################################      
  - platform: template
    sensors:  
      unifi_usg:
        entity_id: device_tracker.unifi_usg
        friendly_name: Unifi USG
        icon_template: mdi:network-router
        value_template: >
          {% if is_state('device_tracker.unifi_usg', 'home') %}
            up
          {% else %}
            down
          {% endif %} 
      unifi_switch:
        entity_id: device_tracker.unifi_switch
        friendly_name: Unifi Switch
        icon_template: mdi:switch
        value_template: >
          {% if is_state('device_tracker.unifi_switch', 'home') %}
            up
          {% else %}
            down
          {% endif %}  
      unifi_ap_living:
        entity_id: device_tracker.unifi_ap_living
        friendly_name: Unifi Acces Point Living
        icon_template: mdi:access-point-network
        value_template: >
          {% if is_state('device_tracker.unifi_ap_living', 'home') %}
            up
          {% else %}
            down
          {% endif %}
      unifi_ap_verdiep_1:
        entity_id: device_tracker.unifi_ap_verdiep_1
        friendly_name: Unifi Acces Point 1e Verdiep
        icon_template: mdi:access-point-network
        value_template: >
          {% if is_state('device_tracker.unifi_ap_verdiep_1', 'home') %}
            up
          {% else %}
            down
          {% endif %}    
      unraid_server:
        entity_id: device_tracker.unraid_server
        friendly_name: Unraid
        icon_template: mdi:nas
        value_template: >
          {% if is_state('device_tracker.unraid_server', 'home') %}
            up
          {% else %}
            down
          {% endif %} 