#### CUSTOMIZE #################################################################

homeassistant:
  customize_glob:
    sensor.unraid_server:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(0,255,0)';
          else return 'rgb(255,0,0)';

glances:
  - host: !secret unraid_server

sensor:
  - platform: template 
    sensors:
      unraid_server:
        entity_id: device_tracker.unraid_server
        friendly_name: Unraid
        icon_template: mdi:nas
        value_template: >
          {% if is_state('device_tracker.unraid_server', 'home') %}
            up
          {% else %}
            down
          {% endif %} 

