#### CUSTOMIZE #################################################################

homeassistant:
  customize_glob:
    sensor.unraid_server:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';

sensor:
  - platform: template 
    sensors:
      unraid_server:
        friendly_name: Unraid
        icon_template: mdi:nas
        value_template: >
          {% if is_state('device_tracker.unraid_server', 'home') %}
            up
          {% else %}
            down
          {% endif %} 

