#### CUSTOMIZE #################################################################
homeassistant:
  customize_glob:
    sensor.unifi_usg:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';
    sensor.unifi_switch:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';
    sensor.unifi_ap_living:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';
    sensor.unifi_ap_verdiep_1:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';
    sensor.unifi_ap_slaapkamer:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';
    sensor.unraid_server:
      templates:
        icon_color: >
          if (state === 'up') return 'rgb(52,152,219)';
          else return 'rgb(95,99,104)';

sensor:
  - platform: unifigateway
    host: !secret unifi_host
    site_id: !secret unifi_site
    username: !secret unifi_username  
    password: !secret unifi_password
    monitored_conditions:
      - www
      - lan
      - wan
      - wlan
      - vpn
      - alerts
      - firmware
  - platform: template
    sensors:
      unifi_gateway_wan_cpu:
        friendly_name: 'CPU percentage'
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['cpu'] }}"
        unit_of_measurement: percentage
      unifi_gateway_wan_mem:
        friendly_name: 'Memory percentage'
        value_template: "{{ states.sensor.unifi_gateway_wan.attributes['gw_system-stats']['mem'] }}"
        unit_of_measurement: percentage
      unifi_gateway_www_xput_down:
        friendly_name: 'USG Speedtest Download'
        unit_of_measurement: Mbps
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.xput_down }}"
        icon_template: mdi:speedometer
      unifi_gateway_www_xput_up:
        friendly_name: 'USG Speedtest Upload'
        unit_of_measurement: Mbps
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.xput_up }}"
        icon_template: mdi:speedometer
      unifi_gateway_www_speedtest_ping:
        friendly_name: 'USG Speedtest Ping'
        unit_of_measurement: ms
        value_template: "{{ states.sensor.unifi_gateway_www.attributes.speedtest_ping }}"
      unifi_gateway_wlan_num_guest:
        friendly_name: 'Guests'
        value_template: '{{ states.sensor.unifi_gateway_wlan.attributes.num_guest }}'
      unifi_usg:
        friendly_name: Unifi USG
        icon_template: mdi:router-network
        value_template: >
          {% if is_state('device_tracker.unifi_usg', 'home') %}
            up
          {% else %}
            down
          {% endif %} 
      unifi_switch:
        friendly_name: Unifi Switch
        icon_template: mdi:switch
        value_template: >
          {% if is_state('device_tracker.unifi_switch', 'home') %}
            up
          {% else %}
            down
          {% endif %}  
      unifi_ap_living:
        friendly_name: AP Living
        icon_template: mdi:access-point-network
        value_template: >
          {% if is_state('device_tracker.unifi_ap_living', 'home') %}
            up
          {% else %}
            down
          {% endif %}
      unifi_ap_verdiep_1:
        friendly_name: AP 1e Verdiep
        icon_template: mdi:access-point-network
        value_template: >
          {% if is_state('device_tracker.unifi_ap_verdiep_1', 'home') %}
            up
          {% else %}
            down
          {% endif %}   
      unifi_ap_slaapkamer:
        friendly_name: AP Slaapkamer
        icon_template: mdi:access-point-network
        value_template: >
          {% if is_state('device_tracker.unifi_ap_slaapkamer', 'home') %}
            up
          {% else %}
            down
          {% endif %}   